name: Update ICS File

on:
  schedule:
    - cron: '0 6 * * *'  # Körs varje dag kl 06:00 UTC
  workflow_dispatch:      # Gör att du kan köra workflow manuellt i GitHub UI

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests icalendar

      - name: Run script to update ICS
        run: python postutdelning.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/postutdelning.ics
          git commit -m "Automatisk uppdatering av postutdelning.ics" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
