name: Uppdatera postutdelning.ics dagligen

on:
  schedule:
    - cron: "0 3 * * *"  # Kör dagligen kl 03:00 UTC (05:00 svensk tid)
  workflow_dispatch:     # Manuell körning

jobs:
  update-ics:
    runs-on: ubuntu-latest

    steps:
      - name: Klona repo
        uses: actions/checkout@v4

      - name: Installera Python och requests
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installera requests
        run: pip install requests

      - name: Kör Python-script
        run: python postutdelning.py

      - name: Lägg till och committa ics-filen
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/postutdelning.ics
          git commit -m "Automatisk uppdatering av postutdelning.ics" || echo "Inga ändringar att committa"
          git push
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

