name: Uppdatera och publicera kalender

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # Kör varje dag kl 07:00 UTC

jobs:
  update-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo utan submoduler
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests icalendar

      - name: Kör uppdateringsskript
        run: python postutdelning.py

      - name: Förbered gh-pages-mapp och publicera
        run: |
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cp docs/postutdelning.ics gh-pages/
          cd gh-pages
          git add postutdelning.ics
          if git diff --cached --quiet; then
            echo "Inga ändringar att committa"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Automatisk uppdatering av kalenderfil"
            git push origin gh-pages
          fi